services:
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE_KAFKA:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: INSIDE_KAFKA
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_INTERNAL: INSIDE_KAFKA
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL_KAFKA
      KAFKA_LISTENER_PORT_EXTERNAL: 9092
      KAFKA_ADVERTISED_LISTENER_EXTERNAL: kafka:9092
      KAFKA_LISTENERS: INSIDE_KAFKA://0.0.0.0:9093
    ports:
      - "9093:9093"
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network


  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app-network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - app-network


  django:
    build:
      context: .
    volumes:
      - ./apps:/app
      - ./config:/app/config
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - .env
    depends_on:
      - kafka
      - elasticsearch
    ports:
      - "8000:8000"

  kafka-consumer:
    build:
      context: ./kafka/consumer
    container_name: kafka-consumer
    depends_on:
      - kafka
      - elasticsearch
    command: python consumer.py
    networks:
      - app-network

  kafka-producer:
      build:
        context: ./kafka/producer
      container_name: kafka-producer
      depends_on:
        - kafka
      command: python producer.py
      networks:
        - app-network

networks:
  app-network:
    driver: bridge